spring:
  boot:
    admin:
      client:
         url: http://localhost:9099/
  application:
    name: cuentasMovimientos
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8
      username: postgres
      password: postgres
      driver-classname: org.postgresql.Driver
#      url: ${SPRING_DATASOURCE_URL}
#      username: ${SPRING_DATASOURCE_USERNAME}
#      password: ${SPRING_DATASOURCE_PASSWORD}
      hikari:
        pool-size: 10
        connection-timeout: 60000 # Adjust timeout as needed
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
    logging:
      level:
        org:
          hibernate:
            type: trace
server:
  port:
    8121
management:
  endpoints:
    web:
      exposure:
        include: "*"