spring:
  boot:
    admin:
      client:
        url: http://localhost:9099/
  application:
    name: informacionPersonal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: postgres
    driver-classname: org.postgresql.Driver
    hikari:
      pool-size: 10 # Adjust pool size as needed
      connection-timeout: 60000 # Adjust timeout as needed
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  docker:
    compose:
      base-dir: "./"  # Directorio base donde se encuentra la carpeta "docker"
      file: "docker/docker-compose.yml"


server:
  context-path: /clientes
  servlet:
    context-path: /clientes
  port: 8022

management:
  endpoints:
    web:
      exposure:
        include: "*"
